import { RSSFeed, FeedItem, Category } from '../types';

function formatDate(ts: number): string {
  return new Date(ts).toLocaleDateString('en-ZA', {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
}

function formatPubDate(dateStr: string): string {
  try {
    return new Date(dateStr).toLocaleDateString('en-ZA', {
      year: 'numeric', month: 'short', day: 'numeric',
    });
  } catch {
    return dateStr;
  }
}

export function exportAsMarkdown(
  feeds: RSSFeed[],
  items: FeedItem[],
  categories: Category[],
  exportedAt: string
): string {
  const lines: string[] = [];

  lines.push(`# Izindaba — RSS Library Export`);
  lines.push(``);
  lines.push(`**Exported:** ${exportedAt} SAST`);
  lines.push(`**Feeds:** ${feeds.length}  |  **Items:** ${items.length}  |  **Categories:** ${categories.length}`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  lines.push(`## Categories`);
  lines.push(``);
  for (const cat of categories) {
    const count = items.filter(i => i.category === cat.name).length;
    lines.push(`- **${cat.name}** — ${count} item${count !== 1 ? 's' : ''}`);
  }
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  for (const feed of feeds) {
    const feedItems = items.filter(i => i.feedId === feed.id);
    lines.push(`## ${feed.title}`);
    lines.push(``);
    lines.push(`- **URL:** ${feed.url}`);
    lines.push(`- **Category:** ${feed.category}`);
    lines.push(`- **Added:** ${formatDate(feed.createdAt)}`);
    if (feed.lastFetched) lines.push(`- **Last Fetched:** ${formatDate(feed.lastFetched)}`);
    lines.push(`- **Items:** ${feedItems.length}`);
    lines.push(``);

    if (feedItems.length === 0) {
      lines.push(`*No items for this feed.*`);
      lines.push(``);
    } else {
      for (const item of feedItems.sort((a, b) => b.fetchedAt - a.fetchedAt)) {
        lines.push(`### ${item.title}`);
        lines.push(``);
        if (item.description) {
          lines.push(`${item.description}`);
          lines.push(``);
        }
        lines.push(`- **Published:** ${formatPubDate(item.pubDate)}`);
        lines.push(`- **Fetched:** ${formatDate(item.fetchedAt)}`);
        lines.push(`- **Link:** [${item.link}](${item.link})`);
        lines.push(``);
      }
    }

    lines.push(`---`);
    lines.push(``);
  }

  lines.push(`*Generated by Izindaba — Your South African RSS Library*`);

  return lines.join('\n');
}

export function exportAsJSON(
  feeds: RSSFeed[],
  items: FeedItem[],
  categories: Category[]
): string {
  const data = {
    exportedAt: new Date().toISOString(),
    summary: {
      feeds: feeds.length,
      items: items.length,
      categories: categories.length,
    },
    categories,
    feeds,
    items,
  };
  return JSON.stringify(data, null, 2);
}

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
